public enum PlayerStatesEnum : int { 
    IDDLE = 0, 
    WALKING = 1, 
    RUNNING = 2, 
    ROLLING = 3, 
    CUTTING = 4, 
    DIGGING = 5,
    WATERING = 6,
    CASTING_FISHING = 7,
    CASTING_FISHING_ON_WATER = 8,
    WAITING_FISHING = 9,
    REELING_FISHING = 10,
    CATCHING_FISHING = 11,
    BACK_FISHING = 12,
    DONT_CATCH_FISHING = 13,
    BUILDING = 14,
    DOING = 15,
};
